name: Example application bundle for MacOS

on:
  push:
    branches: [ master, macos ]
  pull_request:
    branches: [ master, macos ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: OpenImaj Repository must be explicitly allowed because they don't support https.
      uses: whelk-io/maven-settings-xml-action@v15
      with: 
        mirrors: '[{ "id": "openimaj-http-mirror", "mirrorOf": "openimaj-maven", "url": "http://maven.openimaj.org/" }]'
    - name: Build & Install to local maven repository
      run: mvn install -DskipTests -e -B
    - name: Build example
      working-directory: webcam-capture-examples/webcam-capture-macos/
      run: mvn -Djavacpp.platform=macosx-x86_64 package
    - name: Determine module dependencies
      working-directory: webcam-capture-examples/webcam-capture-macos/
      run: echo "::set-output name=JDEPS::$(jdeps --multi-release 11 --print-module-deps --ignore-missing-deps -cp 'target/*:target/dependency/*' target/*.jar)"
      id: jdeps
    - name: Create custom runtime image
      working-directory: webcam-capture-examples/webcam-capture-macos/
      env: 
       DEPS: ${{steps.jdeps.outputs.JDEPS}}
      run: jlink --output jdk14 --add-modules \
       $DEPS \
       --strip-debug --no-man-pages --no-header-files
    - name: Package application image
      working-directory: webcam-capture-examples/webcam-capture-macos/
      run: jpackage --runtime-image jdk14 --verbose --name WebcamFrameExample --input target/ --main-jar $(basename target/*.jar) --main-class WebcamFrameExample -t app-image --resource-dir ./res
    - run: tar -cvf WebcamFrameExample.tar WebcamFrameExample.app
      working-directory: webcam-capture-examples/webcam-capture-macos/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: webcam-capture-examples/webcam-capture-macos/WebcamFrameExample.tar
